package message;

/**
 * Interface for all user-facing messages generated by MeeBot.
 * <p>Implementing classes should:
 * <li>define specific types of messages (e.g., success, error, confirmation) to be displayed to the user.</li>
 */
public interface Message {

    /**
     * Retrieves the message content for UI components
     */
    String message();
}
